drop trigger if exists on_auth_user_created on auth.users;
drop policy if exists "Public Access" on storage.objects;
drop policy if exists "Auth Insert" on storage.objects;
drop policy if exists "Auth Update" on storage.objects;
drop policy if exists "Auth Delete" on storage.objects;
drop policy if exists "voice_notes_read" on storage.objects;
drop policy if exists "voice_notes_insert" on storage.objects;
drop policy if exists "stories_media_read" on storage.objects;
drop policy if exists "stories_media_insert" on storage.objects;
drop policy if exists "music_read" on storage.objects;
drop policy if exists "music_insert" on storage.objects;
drop policy if exists "Public Access Karaoke Tracks" on storage.objects;
drop policy if exists "Authenticated users can upload tracks" on storage.objects;
drop policy if exists "Public Access Karaoke Performances" on storage.objects;
drop policy if exists "Authenticated users can upload performances" on storage.objects;
