/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as RoomIdRouteImport } from './routes/room.$id'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppMusicRouteImport } from './routes/_app.music'
import { Route as AppMessagesRouteImport } from './routes/_app.messages'
import { Route as AppExploreRouteImport } from './routes/_app.explore'
import { Route as AppEventsRouteImport } from './routes/_app.events'
import { Route as AppCommunitiesRouteImport } from './routes/_app.communities'
import { Route as AppProfileIndexRouteImport } from './routes/_app.profile.index'
import { Route as AppProfileIdRouteImport } from './routes/_app.profile.$id'
import { Route as AppCommunityIdRouteImport } from './routes/_app.community.$id'

const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const RoomIdRoute = RoomIdRouteImport.update({
  id: '/room/$id',
  path: '/room/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMusicRoute = AppMusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunitiesRoute = AppCommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileIdRoute = AppProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityIdRoute = AppCommunityIdRouteImport.update({
  id: '/community/$id',
  path: '/community/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/stories': typeof StoriesRoute
  '/communities': typeof AppCommunitiesRoute
  '/events': typeof AppEventsRoute
  '/explore': typeof AppExploreRoute
  '/messages': typeof AppMessagesRoute
  '/music': typeof AppMusicRoute
  '/notifications': typeof AppNotificationsRoute
  '/settings': typeof AppSettingsRoute
  '/chat/$id': typeof ChatIdRoute
  '/room/$id': typeof RoomIdRoute
  '/community/$id': typeof AppCommunityIdRoute
  '/profile/$id': typeof AppProfileIdRoute
  '/profile/': typeof AppProfileIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/stories': typeof StoriesRoute
  '/communities': typeof AppCommunitiesRoute
  '/events': typeof AppEventsRoute
  '/explore': typeof AppExploreRoute
  '/messages': typeof AppMessagesRoute
  '/music': typeof AppMusicRoute
  '/notifications': typeof AppNotificationsRoute
  '/settings': typeof AppSettingsRoute
  '/chat/$id': typeof ChatIdRoute
  '/room/$id': typeof RoomIdRoute
  '/': typeof AppIndexRoute
  '/community/$id': typeof AppCommunityIdRoute
  '/profile/$id': typeof AppProfileIdRoute
  '/profile': typeof AppProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/stories': typeof StoriesRoute
  '/_app/communities': typeof AppCommunitiesRoute
  '/_app/events': typeof AppEventsRoute
  '/_app/explore': typeof AppExploreRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/music': typeof AppMusicRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/chat/$id': typeof ChatIdRoute
  '/room/$id': typeof RoomIdRoute
  '/_app/': typeof AppIndexRoute
  '/_app/community/$id': typeof AppCommunityIdRoute
  '/_app/profile/$id': typeof AppProfileIdRoute
  '/_app/profile/': typeof AppProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/stories'
    | '/communities'
    | '/events'
    | '/explore'
    | '/messages'
    | '/music'
    | '/notifications'
    | '/settings'
    | '/chat/$id'
    | '/room/$id'
    | '/community/$id'
    | '/profile/$id'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/stories'
    | '/communities'
    | '/events'
    | '/explore'
    | '/messages'
    | '/music'
    | '/notifications'
    | '/settings'
    | '/chat/$id'
    | '/room/$id'
    | '/'
    | '/community/$id'
    | '/profile/$id'
    | '/profile'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/stories'
    | '/_app/communities'
    | '/_app/events'
    | '/_app/explore'
    | '/_app/messages'
    | '/_app/music'
    | '/_app/notifications'
    | '/_app/settings'
    | '/chat/$id'
    | '/room/$id'
    | '/_app/'
    | '/_app/community/$id'
    | '/_app/profile/$id'
    | '/_app/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  StoriesRoute: typeof StoriesRoute
  ChatIdRoute: typeof ChatIdRoute
  RoomIdRoute: typeof RoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/room/$id': {
      id: '/room/$id'
      path: '/room/$id'
      fullPath: '/room/$id'
      preLoaderRoute: typeof RoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/music': {
      id: '/_app/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof AppMusicRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events': {
      id: '/_app/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/communities': {
      id: '/_app/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof AppCommunitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/$id': {
      id: '/_app/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof AppProfileIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community/$id': {
      id: '/_app/community/$id'
      path: '/community/$id'
      fullPath: '/community/$id'
      preLoaderRoute: typeof AppCommunityIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCommunitiesRoute: typeof AppCommunitiesRoute
  AppEventsRoute: typeof AppEventsRoute
  AppExploreRoute: typeof AppExploreRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppMusicRoute: typeof AppMusicRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCommunityIdRoute: typeof AppCommunityIdRoute
  AppProfileIdRoute: typeof AppProfileIdRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCommunitiesRoute: AppCommunitiesRoute,
  AppEventsRoute: AppEventsRoute,
  AppExploreRoute: AppExploreRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppMusicRoute: AppMusicRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppCommunityIdRoute: AppCommunityIdRoute,
  AppProfileIdRoute: AppProfileIdRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  StoriesRoute: StoriesRoute,
  ChatIdRoute: ChatIdRoute,
  RoomIdRoute: RoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
